### ISSUE TITLE
ParseError on datefield example

### ISSUE THREAD

**Issue by pyjsorg** [pyjs/original-pyjs#30]
<b>What steps will reproduce the problem?</b>
1. build and installed pyjs
2. cd examples
3. python datefield

<b>What is the expected output? What do you see instead?</b>
expected: compilation succeeds.  Instead I get:

Building : DateField
PYJSPATH : [
    /Users/msyang/tmp/pyjamas/examples/datefield
    /Users/msyang/tmp/pyjamas/library
    /Users/msyang/tmp/pyjamas/addons
]
Translating file : /Users/msyang/tmp/pyjamas/examples/datefield/DateField.py
Traceback (most recent call last):
  File &quot;/Users/msyang/tmp/pyjamas/bin/pyjsbuild&quot;, line 21, in &lt;module&gt;
    pyjs.browser.build_script()
  File &quot;/Users/msyang/tmp/pyjamas/pyjs/src/pyjs/browser.py&quot;, line 539, in build_script
    runtime_options, args)
  File &quot;/Users/msyang/tmp/pyjamas/pyjs/src/pyjs/browser.py&quot;, line 392, in build
    l()
  File &quot;/Users/msyang/tmp/pyjamas/pyjs/src/pyjs/linker.py&quot;, line 275, in **call**
    self.visit_modules(self.modules, platform)
  File &quot;/Users/msyang/tmp/pyjamas/pyjs/src/pyjs/linker.py&quot;, line 329, in visit_modules
    self.visit_module(p, override_paths, platform, module_name=mn)
  File &quot;/Users/msyang/tmp/pyjamas/pyjs/src/pyjs/linker.py&quot;, line 382, in visit_module
    self.keep_lib_files)
  File &quot;/Users/msyang/tmp/pyjamas/pyjs/src/pyjs/linker.py&quot;, line 151, in out_translate
    raise translator.TranslationError(stderr_value, None)
pyjs.translator_proto.TranslationError:  line Unknown:
Traceback (most recent call last):
  File &quot;/Users/msyang/tmp/pyjamas/pyjs/src/pyjs/translator.py&quot;, line 69, in &lt;module&gt;
    main()
  File &quot;/Users/msyang/tmp/pyjamas/pyjs/src/pyjs/translator.py&quot;, line 56, in main
    **get_compile_options(options))
  File &quot;/Users/msyang/tmp/pyjamas/pyjs/src/pyjs/translator_proto.py&quot;, line 4421, in translate
    current_tree = compiler.parseFile(src)
  File &quot;/Users/msyang/tmp/pyjamas/pyjs/src/pyjs/lib_trans/pycompiler/transformer.py&quot;, line 51, in parseFile
    return parse(src)
  File &quot;/Users/msyang/tmp/pyjamas/pyjs/src/pyjs/lib_trans/pycompiler/transformer.py&quot;, line 55, in parse
    return Transformer().parsesuite(buf)
  File &quot;/Users/msyang/tmp/pyjamas/pyjs/src/pyjs/lib_trans/pycompiler/transformer.py&quot;, line 132, in parsesuite
    return self.transform(parser.suite(text))
  File &quot;/Users/msyang/tmp/pyjamas/pyjs/src/pyjs/lib_trans/pyparser/**init**.py&quot;, line 8, in suite
    return d.parse_string(text)
  File &quot;/Users/msyang/tmp/pyjamas/pyjs/src/pyjs/lib_trans/pyparser/driver.py&quot;, line 104, in parse_string
    return self.parse_tokens(tokens, debug)
  File &quot;/Users/msyang/tmp/pyjamas/pyjs/src/pyjs/lib_trans/pyparser/driver.py&quot;, line 69, in parse_tokens
    if p.addtoken(type, value, (prefix, start)):
  File &quot;/Users/msyang/tmp/pyjamas/pyjs/src/pyjs/lib_trans/pyparser/parse.py&quot;, line 138, in addtoken
    ilabel = self.classify(type, value, context)
  File &quot;/Users/msyang/tmp/pyjamas/pyjs/src/pyjs/lib_trans/pyparser/parse.py&quot;, line 194, in classify
    raise ParseError(&quot;bad token&quot;, type, value, context)
pyparser.parse.ParseError: bad token: type=55, value='\xef', context=('', (1, 0))

None

What version of Pyjamas are you using?  which svn revision number?
On what operating system?

git pull from git://pyjs.org/git/pyjamas.git commit 65b360c
python 2.7.2 on Mac OS X or python 2.7.1 on Ubuntu 11.04

If using PyJS, what compiler options did you use?

None.

Please provide any additional information below.

DateField.py module says &quot;Copyright (C) 2009 Yit Choong (http://code.google.com/u/yitchoong/)&quot;

_Original issue: http://code.google.com/p/pyjamas/issues/detail?id=693 (February 25, 2012 15:00:54)_

**Comment by pyjsorg** [comment]
_From yangofz...@gmail.com on February 25, 2012 15:19:26:_
Compiled correctly on commit 41c8553

$ git log
...
commit 41c8553ee141e2320907ff9222738b33cf069f91
Author: lkcl lkcl@7a2bd370-bda8-463c-979e-2900ccfb811e
Date:   Sat Nov 7 12:00:45 2009 +0000

```
forgot somehow to add Yi Choong to credits file
```

**Comment by pyjsorg** [comment]
_From yangofz...@gmail.com on February 25, 2012 15:33:47:_
$ git bisect good
a1112e8f635dfff3bcdbdc08988963e6fdaf4c9f is the first bad commit
commit a1112e8f635dfff3bcdbdc08988963e6fdaf4c9f
Author: Daniel Kluev dan.kluev@gmail.com
Date:   Sun Jun 12 18:48:14 2011 +1100

```
Removed --internal-ast option, as its always on
```

:040000 040000 741cb7560463f3a96aba9ac2276ab064bfb618d7 f03b26bb1f14e51d25d8772dd9ba9fa89cc3984e M      pyjs

**Comment by pyjsorg** [comment]
_From yangofz...@gmail.com on February 25, 2012 15:38:19:_
going any further (past a1112e8f63) throws the following compiler error:

Building : DateField
PYJSPATH : [
    /mnt/run_default/newhome/ubuntu/tmp/pyjamas/examples/datefield
    /mnt/run_default/newhome/ubuntu/tmp/pyjamas/library
    /mnt/run_default/newhome/ubuntu/tmp/pyjamas/addons
]
Traceback (most recent call last):
  File "../../bin/pyjsbuild", line 21, in <module>
    pyjs.browser.build_script()
  File "/mnt/run_default/newhome/ubuntu/tmp/pyjamas/pyjs/src/pyjs/browser.py", line 542, in build_script
    runtime_options, args)
  File "/mnt/run_default/newhome/ubuntu/tmp/pyjamas/pyjs/src/pyjs/browser.py", line 376, in build
    if options.internal_ast:
AttributeError: Values instance has no attribute 'internal_ast'
