### ISSUE TITLE
Kitchen Sink Doesn't work in Safari 4.0.3 (on MacOS X 10.4.11, maybe others)

### ISSUE THREAD

**Issue by pyjsorg** [pyjs/original-pyjs#394]
<b>What steps will reproduce the problem?</b>
1. download pyjamas 0.7 pre 1
2. run bootstrap and build examples/kitchenSink
3. open KitchenSink.html in Safari 4.0.3

<b>What is the expected output? What do you see instead?</b>

When I click on the vertical links on the left nothing happens. In the console I get:

TypeError: Result of expression '$wnd.location.href.split('#').**getitem**' [undefined] is not a function.

file:///Users/steve/Desktop/pyjamas-0.7pre1/examples/kitchensink/output/KitchenSink.safari.cache.html:6916

What version of Pyjamas are you using?  which svn revision number? (0.7 pre-1)
On what operating system? MacOS-X 10.4.11

<b>If using PyJS, have you attached a javascript stack trace,</b>
<b>from IE's Script Debugger or from Firefox Venkman / Firebug?</b>
Have you attached a stack trace from using &quot;-d&quot; compiler option?

<b>If using PyJD, have you attached a python stack trace?</b>

<b>If using PyJS, what compiler options did you use?</b>

<b>Please provide any additional information below.</b>

_Original issue: http://code.google.com/p/pyjamas/issues/detail?id=325 (November 09, 2009 10:19:34)_

**Comment by pyjsorg** [comment]
_From cornelis...@gmail.com on November 09, 2009 13:56:04:_
Thanks. This should be fixed in the current svn. Could you check?

**Comment by pyjsorg** [comment]
_From stevespi...@gmail.com on November 18, 2009 20:45:09:_
Ack.. I'm try to test the svn version, but it looks like there's an issue with the mac's non-case-sensitive 
filesystem that's gumming up my svn checkout:

A    pyjamas/tags/release_0_4p1/examples/widgets/public/images/Clock.png
A    pyjamas/tags/release_0_4p1/examples/widgets/public/images/clock.png
svn: In directory 'pyjamas/tags/release_0_4p1/examples/widgets/public/images'
svn: Can't open file 'pyjamas/tags/release_0_4p1/examples/widgets/public/images/.svn/tmp/text-
base/clock.png.svn-base': No such file or directory
vh10-96:~/Development steve$ 

I guess not many folks are using mac os?

-steve
